"""empty message

Revision ID: 93ebfbc6fe4c
Revises: add_user_boolean_columns
Create Date: 2026-01-25 13:15:50.977497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '93ebfbc6fe4c'
down_revision: Union[str, Sequence[str], None] = 'add_user_boolean_columns'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enable pgvector extension before creating tables with Vector columns
    op.execute(sa.text('CREATE EXTENSION IF NOT EXISTS vector'))
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories'))
    )
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['connected_apps.id'], name=op.f('fk_notes_source_id_connected_apps')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notes_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notes'))
    )
    op.create_index(op.f('ix_notes_source_id'), 'notes', ['source_id'], unique=False)
    op.create_index(op.f('ix_notes_type'), 'notes', ['type'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position_start', sa.Integer(), nullable=False),
    sa.Column('position_end', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(1536), nullable=True),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], name=op.f('fk_chunks_note_id_notes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chunks'))
    )
    op.create_index(op.f('ix_chunks_note_id'), 'chunks', ['note_id'], unique=False)
    op.create_table('note_categories',
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_note_categories_category_id_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], name=op.f('fk_note_categories_note_id_notes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('note_id', 'category_id', name=op.f('pk_note_categories'))
    )
    op.create_index(op.f('ix_note_categories_category_id'), 'note_categories', ['category_id'], unique=False)
    op.create_index(op.f('ix_note_categories_note_id'), 'note_categories', ['note_id'], unique=False)
    op.create_table('relationships',
    sa.Column('note_a_id', sa.Integer(), nullable=False),
    sa.Column('note_b_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['note_a_id'], ['notes.id'], name=op.f('fk_relationships_note_a_id_notes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['note_b_id'], ['notes.id'], name=op.f('fk_relationships_note_b_id_notes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('note_a_id', 'note_b_id', name=op.f('pk_relationships'))
    )
    op.create_index(op.f('ix_relationships_note_a_id'), 'relationships', ['note_a_id'], unique=False)
    op.create_index(op.f('ix_relationships_note_b_id'), 'relationships', ['note_b_id'], unique=False)
    op.create_index(op.f('ix_relationships_type'), 'relationships', ['type'], unique=False)
    op.add_column('users', sa.Column('username', sa.String(), nullable=False))
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'username')
    op.drop_index(op.f('ix_relationships_type'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_note_b_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_note_a_id'), table_name='relationships')
    op.drop_table('relationships')
    op.drop_index(op.f('ix_note_categories_note_id'), table_name='note_categories')
    op.drop_index(op.f('ix_note_categories_category_id'), table_name='note_categories')
    op.drop_table('note_categories')
    op.drop_index(op.f('ix_chunks_note_id'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_notes_type'), table_name='notes')
    op.drop_index(op.f('ix_notes_source_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
